//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinapse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 500")]
        public global::System.Drawing.Point graph_Location {
            get {
                return ((global::System.Drawing.Point)(this["graph_Location"]));
            }
            set {
                this["graph_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point main_Location {
            get {
                return ((global::System.Drawing.Point)(this["main_Location"]));
            }
            set {
                this["main_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState main_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["main_WindowState"]));
            }
            set {
                this["main_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool graph_Autoupdate {
            get {
                return ((bool)(this["graph_Autoupdate"]));
            }
            set {
                this["graph_Autoupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size main_Size {
            get {
                return ((global::System.Drawing.Size)(this["main_Size"]));
            }
            set {
                this["main_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool graph_Launch {
            get {
                return ((bool)(this["graph_Launch"]));
            }
            set {
                this["graph_Launch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int graph_UpdateRate {
            get {
                return ((int)(this["graph_UpdateRate"]));
            }
            set {
                this["graph_UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int display_UpdateRate {
            get {
                return ((int)(this["display_UpdateRate"]));
            }
            set {
                this["display_UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("517, 276")]
        public global::System.Drawing.Size graph_Size {
            get {
                return ((global::System.Drawing.Size)(this["graph_Size"]));
            }
            set {
                this["graph_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool main_AutoSwitchToTrainingTab {
            get {
                return ((bool)(this["main_AutoSwitchToTrainingTab"]));
            }
            set {
                this["main_AutoSwitchToTrainingTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool graph_Disable {
            get {
                return ((bool)(this["graph_Disable"]));
            }
            set {
                this["graph_Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool training_Autosave {
            get {
                return ((bool)(this["training_Autosave"]));
            }
            set {
                this["training_Autosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool training_Crossvalidation {
            get {
                return ((bool)(this["training_Crossvalidation"]));
            }
            set {
                this["training_Crossvalidation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int training_AutosaveEpochs {
            get {
                return ((int)(this["training_AutosaveEpochs"]));
            }
            set {
                this["training_AutosaveEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection history_Networks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["history_Networks"]));
            }
            set {
                this["history_Networks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection history_Database {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["history_Database"]));
            }
            set {
                this["history_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection history_Workplace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["history_Workplace"]));
            }
            set {
                this["history_Workplace"] = value;
            }
        }
    }
}
