//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinapse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point main_Location {
            get {
                return ((global::System.Drawing.Point)(this["main_Location"]));
            }
            set {
                this["main_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState main_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["main_WindowState"]));
            }
            set {
                this["main_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool graph_Autoupdate {
            get {
                return ((bool)(this["graph_Autoupdate"]));
            }
            set {
                this["graph_Autoupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size main_Size {
            get {
                return ((global::System.Drawing.Size)(this["main_Size"]));
            }
            set {
                this["main_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool graph_Launch {
            get {
                return ((bool)(this["graph_Launch"]));
            }
            set {
                this["graph_Launch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int graph_UpdateRate {
            get {
                return ((int)(this["graph_UpdateRate"]));
            }
            set {
                this["graph_UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool main_AutoSwitchToTrainingTab {
            get {
                return ((bool)(this["main_AutoSwitchToTrainingTab"]));
            }
            set {
                this["main_AutoSwitchToTrainingTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool graph_Disable {
            get {
                return ((bool)(this["graph_Disable"]));
            }
            set {
                this["graph_Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool training_Autosave {
            get {
                return ((bool)(this["training_Autosave"]));
            }
            set {
                this["training_Autosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool training_Crossvalidation {
            get {
                return ((bool)(this["training_Crossvalidation"]));
            }
            set {
                this["training_Crossvalidation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int training_AutosaveEpochs {
            get {
                return ((int)(this["training_AutosaveEpochs"]));
            }
            set {
                this["training_AutosaveEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool history_AutoScroll {
            get {
                return ((bool)(this["history_AutoScroll"]));
            }
            set {
                this["history_AutoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool training_LayerAutoSwitch {
            get {
                return ((bool)(this["training_LayerAutoSwitch"]));
            }
            set {
                this["training_LayerAutoSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int training_LayerAutoSwitchEpochs {
            get {
                return ((int)(this["training_LayerAutoSwitchEpochs"]));
            }
            set {
                this["training_LayerAutoSwitchEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size report_Size {
            get {
                return ((global::System.Drawing.Size)(this["report_Size"]));
            }
            set {
                this["report_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point report_Location {
            get {
                return ((global::System.Drawing.Point)(this["report_Location"]));
            }
            set {
                this["report_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState report_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["report_WindowState"]));
            }
            set {
                this["report_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool main_FirstLoad {
            get {
                return ((bool)(this["main_FirstLoad"]));
            }
            set {
                this["main_FirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool report_FirstLoad {
            get {
                return ((bool)(this["report_FirstLoad"]));
            }
            set {
                this["report_FirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size history_Size {
            get {
                return ((global::System.Drawing.Size)(this["history_Size"]));
            }
            set {
                this["history_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point history_Location {
            get {
                return ((global::System.Drawing.Point)(this["history_Location"]));
            }
            set {
                this["history_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool history_FirstLoad {
            get {
                return ((bool)(this["history_FirstLoad"]));
            }
            set {
                this["history_FirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int display_UpdateRate {
            get {
                return ((int)(this["display_UpdateRate"]));
            }
            set {
                this["display_UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int display_UpdateTime {
            get {
                return ((int)(this["display_UpdateTime"]));
            }
            set {
                this["display_UpdateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool display_UpdateByTime {
            get {
                return ((bool)(this["display_UpdateByTime"]));
            }
            set {
                this["display_UpdateByTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool graph_autoScrollSavepoints {
            get {
                return ((bool)(this["graph_autoScrollSavepoints"]));
            }
            set {
                this["graph_autoScrollSavepoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int training_delay {
            get {
                return ((int)(this["training_delay"]));
            }
            set {
                this["training_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int training_CrossvalidationEpochs {
            get {
                return ((int)(this["training_CrossvalidationEpochs"]));
            }
            set {
                this["training_CrossvalidationEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool behaviour_ShowStartPage {
            get {
                return ((bool)(this["behaviour_ShowStartPage"]));
            }
            set {
                this["behaviour_ShowStartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection mruDocuments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["mruDocuments"]));
            }
            set {
                this["mruDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection mruWorkplaces {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["mruWorkplaces"]));
            }
            set {
                this["mruWorkplaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("web/index.html")]
        public string startpage_path {
            get {
                return ((string)(this["startpage_path"]));
            }
            set {
                this["startpage_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string workplaces_path {
            get {
                return ((string)(this["workplaces_path"]));
            }
            set {
                this["workplaces_path"] = value;
            }
        }
    }
}
